Repository woowa-techcamp-2024/Team4-BF2, pull requests merged in 2024-08, with the labels that each got.

#5 [docs] README.md 초안 작성
  README.md
Labels: 📝Docs

#6 [config] dev 개발 초기 세팅
  .gitignore
  build.gradle
  src/main/resources/application.properties
  src/main/resources/application.yml
Labels: ⚙️Config

#21 [config] mono 모듈을 만들어서 프로젝트 초기 세팅
  mono/build.gradle
  mono/src/main/java/woowa/team4/bff/BffApplication.java
  mono/src/main/resources/application.yml
  settings.gradle
  src/test/java/woowa/team4/bff/BffApplicationTests.java
Labels: ⚙️Config

#30 [config] GitHub AI 코드 리뷰 봇 설정
  .github/workflows/main.yml
Labels: ⚙️Config

#34 [feature] 메뉴 카테고리를 등록할 수 있다
  mono/build.gradle
  mono/src/main/java/woowa/team4/bff/BffApplication.java
  mono/src/main/java/woowa/team4/bff/menu/category/controller/MenuCategoryController.java
  mono/src/main/java/woowa/team4/bff/menu/category/dto/MenuCategoryCreateRequest.java
  mono/src/main/java/woowa/team4/bff/menu/category/dto/MenuCategoryCreateResponse.java
  mono/src/main/java/woowa/team4/bff/menu/category/dto/MenuCategoryDto.java
  mono/src/main/java/woowa/team4/bff/menu/category/entity/MenuCategory.java
  mono/src/main/java/woowa/team4/bff/menu/category/event/MenuCategoryCreateEvent.java
  mono/src/main/java/woowa/team4/bff/menu/category/repository/MenuCategoryRepository.java
  mono/src/main/java/woowa/team4/bff/menu/category/service/MenuCategoryEventListener.java
  mono/src/main/java/woowa/team4/bff/menu/category/service/MenuCategoryService.java
Labels: 💫Feature

#39 [feature] 메뉴 카테고리를 등록, 수정, 삭제할 수 있다.
  mono/build.gradle
  mono/src/main/java/woowa/team4/bff/BffApplication.java
  mono/src/main/java/woowa/team4/bff/menu/category/controller/MenuCategoryController.java
  mono/src/main/java/woowa/team4/bff/menu/category/dto/create/MenuCategoryCreateDto.java
  mono/src/main/java/woowa/team4/bff/menu/category/dto/create/MenuCategoryCreateRequest.java
  mono/src/main/java/woowa/team4/bff/menu/category/dto/create/MenuCategoryCreateResponse.java
  mono/src/main/java/woowa/team4/bff/menu/category/dto/update/MenuCategoryUpdateDto.java
  mono/src/main/java/woowa/team4/bff/menu/category/dto/update/MenuCategoryUpdateRequest.java
  mono/src/main/java/woowa/team4/bff/menu/category/dto/update/MenuCategoryUpdateResponse.java
  mono/src/main/java/woowa/team4/bff/menu/category/entity/MenuCategory.java
  mono/src/main/java/woowa/team4/bff/menu/category/event/MenuCategoryCreateEvent.java
  mono/src/main/java/woowa/team4/bff/menu/category/event/MenuCategoryDeleteEvent.java
  mono/src/main/java/woowa/team4/bff/menu/category/event/MenuCategoryUpdateEvent.java
  mono/src/main/java/woowa/team4/bff/menu/category/exception/MenuCategoryNotFoundException.java
  mono/src/main/java/woowa/team4/bff/menu/category/repository/MenuCategoryRepository.java
  mono/src/main/java/woowa/team4/bff/menu/category/service/MenuCategoryService.java
Labels: 💫Feature

#46 [feature] 단일 메뉴를 수정, 삭제할 수 있다.
  mono/src/main/java/woowa/team4/bff/menu/item/controller/MenuController.java
  mono/src/main/java/woowa/team4/bff/menu/item/dto/update/MenuUpdateDto.java
  mono/src/main/java/woowa/team4/bff/menu/item/dto/update/MenuUpdateRequest.java
  mono/src/main/java/woowa/team4/bff/menu/item/dto/update/MenuUpdateResponse.java
  mono/src/main/java/woowa/team4/bff/menu/item/event/MenuDeleteEvent.java
  mono/src/main/java/woowa/team4/bff/menu/item/event/MenuUpdateEvent.java
  mono/src/main/java/woowa/team4/bff/menu/item/exception/MenuNotFoundException.java
  mono/src/main/java/woowa/team4/bff/menu/item/service/MenuService.java
Labels: 💫Feature

#47 [feature] 가게 등록 API
  mono/build.gradle
  mono/src/main/java/woowa/team4/bff/restaurant/controller/RestaurantController.java
  mono/src/main/java/woowa/team4/bff/restaurant/controller/dto/request/CreateRestaurantRequest.java
  mono/src/main/java/woowa/team4/bff/restaurant/controller/dto/response/RegisterRestaurantResponse.java
  mono/src/main/java/woowa/team4/bff/restaurant/domain/Coordinate.java
  mono/src/main/java/woowa/team4/bff/restaurant/domain/Restaurant.java
  mono/src/main/java/woowa/team4/bff/restaurant/domain/RestaurantRegistrant.java
  mono/src/main/java/woowa/team4/bff/restaurant/entity/RestaurantEntity.java
  mono/src/main/java/woowa/team4/bff/restaurant/event/Event.java
  mono/src/main/java/woowa/team4/bff/restaurant/event/EventPublisher.java
  mono/src/main/java/woowa/team4/bff/restaurant/event/RestaurantRegistrationEvent.java
  mono/src/main/java/woowa/team4/bff/restaurant/event/SpringEventPublisher.java
  mono/src/main/java/woowa/team4/bff/restaurant/repository/RestaurantRepository.java
  mono/src/main/java/woowa/team4/bff/restaurant/service/RestaurantEventProvider.java
  mono/src/main/java/woowa/team4/bff/restaurant/service/RestaurantService.java
  mono/src/main/java/woowa/team4/bff/restaurant/service/RestaurantValidator.java
Labels: 💫Feature

#52 [feature] 메뉴 옵션을 등록할 수 있다.
  mono/src/main/java/woowa/team4/bff/menu/item/dto/create/MenuCreateRequest.java
  mono/src/main/java/woowa/team4/bff/menu/option/controller/MenuOptionController.java
  mono/src/main/java/woowa/team4/bff/menu/option/dto/create/MenuOptionCreateDto.java
  mono/src/main/java/woowa/team4/bff/menu/option/dto/create/MenuOptionCreateRequest.java
  mono/src/main/java/woowa/team4/bff/menu/option/dto/create/MenuOptionCreateResponse.java
  mono/src/main/java/woowa/team4/bff/menu/option/entity/MenuOption.java
  mono/src/main/java/woowa/team4/bff/menu/option/entity/MenuOptionDetail.java
  mono/src/main/java/woowa/team4/bff/menu/option/event/MenuOptionCreateEvent.java
  mono/src/main/java/woowa/team4/bff/menu/option/repository/MenuOptionDetailRepository.java
  mono/src/main/java/woowa/team4/bff/menu/option/repository/MenuOptionRepository.java
  mono/src/main/java/woowa/team4/bff/menu/option/service/MenuOptionService.java
  mono/src/main/java/woowa/team4/bff/menu/utils/constants.java
Labels: 💫Feature

#53 [feature] elastic search create & update, search keyword
  mono/build.gradle
  mono/src/main/java/woowa/team4/bff/common/aop/MethodLogging.java
  mono/src/main/java/woowa/team4/bff/common/aop/MethodLoggingAspect.java
  mono/src/main/java/woowa/team4/bff/restaurant/service/RestaurantService.java
  mono/src/main/java/woowa/team4/bff/search/controller/SearchApiController.java
  mono/src/main/java/woowa/team4/bff/search/document/MenuSearchDocument.java
  mono/src/main/java/woowa/team4/bff/search/document/RestaurantSearchDocument.java
  mono/src/main/java/woowa/team4/bff/search/domain/MenuSearch.java
  mono/src/main/java/woowa/team4/bff/search/domain/RestaurantSearch.java
  mono/src/main/java/woowa/team4/bff/search/domain/RestaurantSearchResult.java
  mono/src/main/java/woowa/team4/bff/search/repository/MenuSearchMapper.java
  mono/src/main/java/woowa/team4/bff/search/repository/MenuSearchRepository.java
  mono/src/main/java/woowa/team4/bff/search/repository/RestaurantEntityRepository.java
  mono/src/main/java/woowa/team4/bff/search/repository/RestaurantSearchMapper.java
  mono/src/main/java/woowa/team4/bff/search/repository/RestaurantSearchRepository.java
  mono/src/main/java/woowa/team4/bff/search/repository/SearchIndexManageRepository.java
  mono/src/main/java/woowa/team4/bff/search/repository/SearchRepository.java
  mono/src/main/java/woowa/team4/bff/search/service/SearchIndexManageService.java
  mono/src/main/java/woowa/team4/bff/search/service/SearchService.java
  mono/src/main/java/woowa/team4/bff/search/service/command/CreateRestaurantSearchCommand.java
  mono/src/main/java/woowa/team4/bff/search/service/command/SearchRestaurantCommand.java
  mono/src/main/java/woowa/team4/bff/search/service/command/UpdateRestaurantSearchCommand.java
  mono/src/main/resources/application.yml
Labels: 💫Feature

#54 [feature] 리뷰를 추가할 수 있다.
  mono/src/main/java/woowa/team4/bff/review/controller/ReviewController.java
  mono/src/main/java/woowa/team4/bff/review/dto/create/ReviewCreateDto.java
  mono/src/main/java/woowa/team4/bff/review/dto/create/ReviewCreateRequest.java
  mono/src/main/java/woowa/team4/bff/review/dto/create/ReviewCreateResponse.java
  mono/src/main/java/woowa/team4/bff/review/entity/Review.java
  mono/src/main/java/woowa/team4/bff/review/entity/ReviewMenu.java
  mono/src/main/java/woowa/team4/bff/review/repository/ReviewRepository.java
  mono/src/main/java/woowa/team4/bff/review/service/ReviewService.java
Labels: 💫Feature

#56 [feature] 메뉴의 옵션을 수정, 삭제할 수 있다.
  mono/src/main/java/woowa/team4/bff/menu/option/controller/MenuOptionController.java
  mono/src/main/java/woowa/team4/bff/menu/option/dto/update/MenuOptionUpdateDto.java
  mono/src/main/java/woowa/team4/bff/menu/option/dto/update/MenuOptionUpdateRequest.java
  mono/src/main/java/woowa/team4/bff/menu/option/entity/MenuOption.java
  mono/src/main/java/woowa/team4/bff/menu/option/entity/MenuOptionDetail.java
  mono/src/main/java/woowa/team4/bff/menu/option/event/MenuOptionDeleteEvent.java
  mono/src/main/java/woowa/team4/bff/menu/option/event/MenuOptionUpdateEvent.java
  mono/src/main/java/woowa/team4/bff/menu/option/exception/MenuOptionNotFoundException.java
  mono/src/main/java/woowa/team4/bff/menu/option/service/MenuOptionService.java
Labels: 💫Feature

#57 [feature] 메뉴 옵션을 등록, 수정, 삭제할 수 있다.
  mono/src/main/java/woowa/team4/bff/menu/item/dto/create/MenuCreateRequest.java
  mono/src/main/java/woowa/team4/bff/menu/option/controller/MenuOptionController.java
  mono/src/main/java/woowa/team4/bff/menu/option/dto/create/MenuOptionCreateDto.java
  mono/src/main/java/woowa/team4/bff/menu/option/dto/create/MenuOptionCreateRequest.java
  mono/src/main/java/woowa/team4/bff/menu/option/dto/create/MenuOptionCreateResponse.java
  mono/src/main/java/woowa/team4/bff/menu/option/dto/update/MenuOptionUpdateDto.java
  mono/src/main/java/woowa/team4/bff/menu/option/dto/update/MenuOptionUpdateRequest.java
  mono/src/main/java/woowa/team4/bff/menu/option/entity/MenuOption.java
  mono/src/main/java/woowa/team4/bff/menu/option/entity/MenuOptionDetail.java
  mono/src/main/java/woowa/team4/bff/menu/option/event/MenuOptionCreateEvent.java
  mono/src/main/java/woowa/team4/bff/menu/option/event/MenuOptionDeleteEvent.java
  mono/src/main/java/woowa/team4/bff/menu/option/event/MenuOptionUpdateEvent.java
  mono/src/main/java/woowa/team4/bff/menu/option/exception/MenuOptionNotFoundException.java
  mono/src/main/java/woowa/team4/bff/menu/option/repository/MenuOptionDetailRepository.java
  mono/src/main/java/woowa/team4/bff/menu/option/repository/MenuOptionRepository.java
  mono/src/main/java/woowa/team4/bff/menu/option/service/MenuOptionService.java
  mono/src/main/java/woowa/team4/bff/menu/utils/constants.java
Labels: 💫Feature

#61 [refactor] 패키지 이름 변경
  domain/common-domain/src/main/java/woowa/team4/bff/domain/common/utils/PrefixedUuidConverter.java
Labels: ♻️Refactor

#62 [refactor] restaurant 모듈 분리 및 팀 컨벤션 준수
  domain/restaurant-domain-rdb/src/main/java/woowa/team4/bff/restaurant/command/RestaurantRegistrationCommand.java
  domain/restaurant-domain-rdb/src/main/java/woowa/team4/bff/restaurant/domain/Restaurant.java
  domain/restaurant-domain-rdb/src/main/java/woowa/team4/bff/restaurant/entity/RestaurantEntity.java
  domain/restaurant-domain-rdb/src/main/java/woowa/team4/bff/restaurant/repository/RestaurantFinder.java
  domain/restaurant-domain-rdb/src/main/java/woowa/team4/bff/restaurant/repository/RestaurantRegistrant.java
  domain/restaurant-domain-rdb/src/main/java/woowa/team4/bff/restaurant/repository/RestaurantRepository.java
  domain/restaurant-domain-rdb/src/main/java/woowa/team4/bff/restaurant/service/RestaurantEventProvider.java
  domain/restaurant-domain-rdb/src/main/java/woowa/team4/bff/restaurant/service/RestaurantService.java
  domain/restaurant-domain-rdb/src/main/java/woowa/team4/bff/restaurant/service/RestaurantValidator.java
  mono/build.gradle
  mono/src/main/java/woowa/team4/bff/event/menu/MenuCreateEvent.java
  mono/src/main/java/woowa/team4/bff/event/menu/MenuUpdateEvent.java
  mono/src/main/java/woowa/team4/bff/event/restaurant/RestaurantCreateEvent.java
  mono/src/main/java/woowa/team4/bff/event/restaurant/RestaurantUpdateEvent.java
  mono/src/main/java/woowa/team4/bff/restaurant/controller/RestaurantController.java
  mono/src/main/java/woowa/team4/bff/restaurant/controller/create/RegisterRestaurantRequest.java
  mono/src/main/java/woowa/team4/bff/restaurant/controller/create/RegisterRestaurantResponse.java
  mono/src/main/java/woowa/team4/bff/restaurant/controller/dto/request/CreateRestaurantRequest.java
  mono/src/main/java/woowa/team4/bff/restaurant/domain/Coordinate.java
  mono/src/main/java/woowa/team4/bff/restaurant/domain/Restaurant.java
  mono/src/main/java/woowa/team4/bff/restaurant/domain/RestaurantRegistrant.java
  mono/src/main/java/woowa/team4/bff/restaurant/event/RestaurantRegistrationEvent.java
  mono/src/main/java/woowa/team4/bff/restaurant/service/RestaurantService.java
Labels: ♻️Refactor

#63 [refactor] review 모듈 분리 및 팀 컨벤션 준수
  domain/review-domain-rdb/src/main/java/woowa/team4/bff/review/command/ReviewCreateCommand.java
  domain/review-domain-rdb/src/main/java/woowa/team4/bff/review/domain/Review.java
  domain/review-domain-rdb/src/main/java/woowa/team4/bff/review/entity/ReviewEntity.java
  domain/review-domain-rdb/src/main/java/woowa/team4/bff/review/entity/ReviewMenuEntity.java
  domain/review-domain-rdb/src/main/java/woowa/team4/bff/review/repository/ReviewEntityRepository.java
  domain/review-domain-rdb/src/main/java/woowa/team4/bff/review/repository/ReviewRepository.java
  domain/review-domain-rdb/src/main/java/woowa/team4/bff/review/service/ReviewService.java
  mono/src/main/java/woowa/team4/bff/review/controller/ReviewController.java
  mono/src/main/java/woowa/team4/bff/review/controller/create/ReviewCreateRequest.java
  mono/src/main/java/woowa/team4/bff/review/controller/create/ReviewCreateResponse.java
  mono/src/main/java/woowa/team4/bff/review/dto/create/ReviewCreateDto.java
  mono/src/main/java/woowa/team4/bff/review/dto/create/ReviewCreateRequest.java
  mono/src/main/java/woowa/team4/bff/review/dto/create/ReviewCreateResponse.java
  mono/src/main/java/woowa/team4/bff/review/repository/ReviewRepository.java
  mono/src/main/java/woowa/team4/bff/review/service/ReviewService.java
Labels: ♻️Refactor

#69 [feature] 검색어 입력시 검색 목록 응답
  domain/restaurant-domain-rdb/src/main/java/woowa/team4/bff/restaurant/command/RestaurantRegistrationCommand.java
  domain/restaurant-domain-rdb/src/main/java/woowa/team4/bff/restaurant/domain/Restaurant.java
  domain/restaurant-domain-rdb/src/main/java/woowa/team4/bff/restaurant/entity/RestaurantEntity.java
  domain/restaurant-domain-rdb/src/main/java/woowa/team4/bff/restaurant/service/RestaurantService.java
  domain/search-domain-es/src/main/java/woowa/team4/bff/search/domain/MenuSearch.java
  domain/search-domain-es/src/main/java/woowa/team4/bff/search/domain/RestaurantSearch.java
  domain/search-domain-es/src/main/java/woowa/team4/bff/search/service/SearchIndexManageService.java
  domain/search-domain-rdb/src/main/java/woowa/team4/bff/search/domain/RestaurantSearchResult.java
  domain/search-domain-rdb/src/main/java/woowa/team4/bff/search/repository/RestaurantEntityRepository.java
  domain/search-domain-rdb/src/main/java/woowa/team4/bff/search/repository/RestaurantSearchResultRepository.java
  mono/src/main/java/woowa/team4/bff/restaurant/controller/create/RegisterRestaurantRequest.java
  mono/src/main/java/woowa/team4/bff/search/service/SearchService.java
Labels: 💫Feature

#67 [fix] ReviewMenu create table 관련 발생 오류 수정
  domain/review-domain-rdb/src/main/java/woowa/team4/bff/review/entity/ReviewEntity.java
  domain/review-domain-rdb/src/main/java/woowa/team4/bff/review/entity/ReviewMenuEntity.java
  mono/src/main/java/woowa/team4/bff/review/controller/ReviewController.java
Labels: 🐛Bug

#76 [fix] 쿼리 수정
  domain/search-domain-rdb/src/main/java/woowa/team4/bff/search/domain/RestaurantSearchResult.java
  domain/search-domain-rdb/src/main/java/woowa/team4/bff/search/repository/RestaurantEntityRepository.java
Labels: 🐛Bug

#78 [fix] Gradle 빌드 오류 수정
  build.gradle
  core-web/build.gradle
  domain/build.gradle
  domain/common-domain/build.gradle
  domain/common-domain/src/main/java/woowa/team4/bff/domain/common/config/JpaAuditingConfiguration.java
  domain/menu-domain-rdb/build.gradle
  domain/restaurant-domain-rdb/build.gradle
  domain/review-domain-rdb/build.gradle
  domain/search-domain-es/build.gradle
  domain/search-domain-rdb/build.gradle
  mono/build.gradle
  mono/src/main/java/woowa/team4/bff/BffApplication.java
Labels: ♻️Refactor, 🐛Bug

#80 [fix] 검색 목록 조회 쿼리 수정
  .gitignore
  domain/restaurant-domain-rdb/src/main/java/woowa/team4/bff/restaurant/repository/RestaurantFinder.java
  domain/restaurant-domain-rdb/src/main/java/woowa/team4/bff/restaurant/repository/RestaurantRepository.java
  domain/search-domain-es/src/main/java/woowa/team4/bff/search/document/MenuSearchDocument.java
  domain/search-domain-es/src/main/java/woowa/team4/bff/search/document/RestaurantSearchDocument.java
  domain/search-domain-rdb/src/main/java/woowa/team4/bff/search/aop/MethodLogging.java
  domain/search-domain-rdb/src/main/java/woowa/team4/bff/search/aop/MethodLoggingAspect.java
  domain/search-domain-rdb/src/main/java/woowa/team4/bff/search/repository/RestaurantSearchResultRepository.java
  mono/src/main/java/woowa/team4/bff/search/controller/SearchApiController.java
  mono/src/main/java/woowa/team4/bff/search/dummy/DummyApiController.java
  mono/src/main/java/woowa/team4/bff/search/service/SearchService.java
  mono/src/main/resources/elasticsearch-settings.json
Labels: 🐛Bug

#83 [config] GitHub Actions 배포 스크립트 추가
  .github/workflows/dev-deploy.yml
Labels: ⚙️Config

#94 [feature] exposure-common-domain
  domain/exposure-common-domain/build.gradle
  domain/exposure-common-domain/src/main/java/woowa/team4/bff/domain/RestaurantSummary.java
  domain/exposure-common-domain/src/main/java/woowa/team4/bff/interfaces/CacheService.java
  domain/exposure-domain/build.gradle
  domain/exposure-domain/src/main/java/woowa/team4/bff/exposure/service/RestaurantExposureListService.java
  settings.gradle
Labels: 💫Feature

#95 [config] 캐시 서버 환경을 구성한다.
  domain/cache-domain-redis/build.gradle
  domain/cache-domain-redis/src/main/java/woowa/team4/bff/cache/redis/service/CacheRedisService.java
  domain/cache-domain-redis/src/main/java/woowa/team4/bff/cache/redis/service/RestaurantCacheService.java
  domain/cache-domain-redis/src/main/java/woowa/team4/bff/cache/redis/service/ReviewStatisticsCacheService.java
  mono/src/main/resources/application.yml
  settings.gradle
Labels: ⚙️Config

#97 [refactor] 리뷰 통계 리팩토링
  domain/review-domain-rdb/build.gradle
  domain/review-domain-rdb/src/main/java/woowa/team4/bff/review/service/ReviewService.java
  domain/review-domain-rdb/src/main/java/woowa/team4/bff/review/service/ReviewStatisticsService.java
  event/review-event/src/main/java/woowa/team4/bff/event/reviewstatistics/ReviewStatisticsUpdateEvent.java
Labels: ♻️Refactor

#100 [feature] 캐시 서비스를 구현한다
  domain/cache-domain-redis/build.gradle
  domain/cache-domain-redis/src/main/java/woowa/team4/bff/cache/redis/config/RedisConfiguration.java
  domain/cache-domain-redis/src/main/java/woowa/team4/bff/cache/redis/exception/JsonConvertException.java
  domain/cache-domain-redis/src/main/java/woowa/team4/bff/cache/redis/repository/RestaurantReviewStatisticsRepository.java
  domain/cache-domain-redis/src/main/java/woowa/team4/bff/cache/redis/service/CacheRedisService.java
  domain/exposure-domain/build.gradle
  domain/exposure-domain/src/main/java/woowa/team4/bff/exposure/service/RestaurantExposureListService.java
  domain/review-domain-rdb/src/main/java/woowa/team4/bff/review/service/ReviewStatisticsService.java
  mono/src/main/resources/application.yml
  settings.gradle
Labels: 💫Feature

#104 [refactor] 캐시 서비스를 리팩토링한다.
  domain/cache-domain-redis/src/main/java/woowa/team4/bff/cache/redis/service/CacheManagerService.java
  domain/cache-domain-redis/src/main/java/woowa/team4/bff/cache/redis/service/CacheRedisService.java
  domain/cache-domain-redis/src/main/java/woowa/team4/bff/cache/redis/utils/JsonConverter.java
  domain/cache-domain-redis/src/main/java/woowa/team4/bff/cache/redis/utils/RedisKeyExtractor.java
  domain/restaurant-domain-rdb/src/main/java/woowa/team4/bff/restaurant/repository/RestaurantFinder.java
  domain/search-domain-rdb/src/main/java/woowa/team4/bff/search/repository/RestaurantSummaryEntityRepository.java
Labels: ♻️Refactor

#106 [feature] cache delivery location
  build.gradle
  domain/cache-domain-redis/build.gradle
  domain/cache-domain-redis/src/main/java/woowa/team4/bff/cache/redis/service/CacheManagerService.java
  domain/cache-domain-redis/src/main/java/woowa/team4/bff/cache/redis/service/CacheRedisService.java
  domain/cache-domain-redis/src/main/java/woowa/team4/bff/cache/redis/utils/JsonConverter.java
  domain/cache-domain-redis/src/main/java/woowa/team4/bff/cache/redis/utils/RedisKeyExtractor.java
  domain/cache-domain-redis/src/main/java/woowa/team4/bff/cache/redis/utils/RedisKeyMaker.java
  domain/exposure-common-domain/src/main/java/woowa/team4/bff/interfaces/CacheService.java
  domain/exposure-domain/build.gradle
  domain/exposure-domain/src/main/java/woowa/team4/bff/exposure/service/RestaurantExposureListService.java
  dummy-api/build.gradle
  event/cache-event/build.gradle
  event/cache-event/src/main/java/woowa/team4/bff/event/cache/DeliveryLocationAndKeywordCreateEvent.java
  mono/build.gradle
  mono/src/main/java/woowa/team4/bff/exposure/controller/RestaurantSummaryApiController.java
  settings.gradle
Labels: 💫Feature

#102 [feature] 더비 서버를 생성한다.
  api-client/advertisement-client/build.gradle
  api-client/advertisement-client/src/main/java/woowa/team4/bff/api/client/advertisement/caller/AdvertisementApiCaller.java
  api-client/advertisement-client/src/main/java/woowa/team4/bff/api/client/advertisement/config/AdvertisementClientConfiguration.java
  api-client/advertisement-client/src/main/java/woowa/team4/bff/api/client/advertisement/request/AdvertisementRequest.java
  api-client/advertisement-client/src/main/java/woowa/team4/bff/api/client/advertisement/response/AdvertisementResponse.java
  api-client/build.gradle
  api-client/common-client/src/main/java/woowa/tema4/bff/api/client/caller/AsyncClientApiCaller.java
  api-client/common-client/src/main/java/woowa/tema4/bff/api/client/caller/SyncClientApiCaller.java
  api-client/common-client/src/main/java/woowa/tema4/bff/api/client/caller/WebClientCaller.java
  api-client/common-client/src/main/java/woowa/tema4/bff/api/client/config/ApiClientConfiguration.java
  api-client/common-client/src/main/java/woowa/tema4/bff/api/client/config/ApiClientProperties.java
  api-client/coupon-client/build.gradle
  api-client/coupon-client/src/main/java/woowa/team4/bff/api/client/coupon/caller/CouponApiCaller.java
  api-client/coupon-client/src/main/java/woowa/team4/bff/api/client/coupon/config/CouponClientConfiguration.java
  api-client/coupon-client/src/main/java/woowa/team4/bff/api/client/coupon/request/CouponRequest.java
  api-client/coupon-client/src/main/java/woowa/team4/bff/api/client/coupon/response/CouponResponse.java
  api-client/delivery-client/build.gradle
  api-client/delivery-client/src/main/java/woowa/team4/bff/api/client/delivery/caller/DeliveryTimeApiCaller.java
  api-client/delivery-client/src/main/java/woowa/team4/bff/api/client/delivery/config/DeliveryClientConfiguration.java
  api-client/delivery-client/src/main/java/woowa/team4/bff/api/client/delivery/request/DeliveryTimeRequest.java
  api-client/delivery-client/src/main/java/woowa/team4/bff/api/client/delivery/response/DeliveryTimeResponse.java
  build.gradle
  domain/exposure-domain/build.gradle
  domain/exposure-domain/src/main/java/woowa/team4/bff/exposure/caller/AsyncExternalApiCaller.java
  domain/exposure-domain/src/main/java/woowa/team4/bff/exposure/caller/SyncExternalApiCaller.java
  domain/exposure-domain/src/main/java/woowa/team4/bff/exposure/service/RestaurantExposureListService.java
  domain/exposure-domain/src/main/resources/application.yml
  external/build.gradle
  external/src/main/java/woowa/team4/external/BffExternalApplication.java
  external/src/main/java/woowa/team4/external/advertisement/AdvertisementController.java
  external/src/main/java/woowa/team4/external/coupon/CouponController.java
  external/src/main/java/woowa/team4/external/delivery/DeliveryTimeController.java
  external/src/main/resources/application.yml
  mono/src/main/resources/application.yml
  settings.gradle
Labels: 💫Feature

#115 [fix] SearchRdbService에 오버라이딩 에러 수정 및 설정 변경
  domain/exposure-domain/build.gradle
  domain/search-domain-es/src/main/java/woowa/team4/bff/search/service/ElasticsearchIndexInitializer.java
  domain/search-domain-rdb/src/main/java/woowa/team4/bff/search/service/SearchRdbService.java
  external/build.gradle
  mono/src/main/resources/application.yml
Labels: ⚙️Config, 🐛Bug

#119 [feature] 가게 검색에 페이지네이션을 적용
  domain/cache-domain-redis/src/main/java/woowa/team4/bff/cache/redis/config/RedisConfiguration.java
  domain/exposure-domain/src/main/java/woowa/team4/bff/exposure/service/RestaurantExposureListService.java
  domain/search-domain-es/src/main/java/woowa/team4/bff/search/service/ElasticsearchIndexInitializer.java
  domain/search-domain-es/src/main/java/woowa/team4/bff/search/service/SearchElasticsearchService.java
  service/search-service/src/main/resources/application.yml
Labels: 💫Feature

#120 [feature] 가게 목록, 가게 등록 화면 추가
  package.json
  view/.gitignore
  view/README.md
  view/eslint.config.js
  view/index.html
  view/package-lock.json
  view/package.json
  view/postcss.config.js
  view/public/logo.png
  view/src/App.css
  view/src/App.jsx
  view/src/assets/arrow-left.svg
  view/src/components/LocationModal.jsx
  view/src/components/RegisterRestaurant.jsx
  view/src/components/RestaurantList.jsx
  view/src/data/koreaDistricts.js
  view/src/fonts/BMHANNAPro.ttf
  view/src/index.css
  view/src/main.jsx
  view/tailwind.config.js
  view/vite.config.js
Labels: 💫Feature

#123 [fix] circuit breaker api 별 동작
  .gitignore
  api-client/common-client/src/main/java/woowa/tema4/bff/api/client/caller/WebClientCaller.java
  api-client/common-client/src/main/java/woowa/tema4/bff/api/client/config/ApiClientConfiguration.java
Labels: 🪓Hotfix

#125 [refactor] 124 cache service async
  .gitignore
  domain/cache-domain-redis/build.gradle
  domain/cache-domain-redis/src/main/java/woowa/team4/bff/cache/redis/service/CacheManagerService.java
  domain/cache-domain-redis/src/main/java/woowa/team4/bff/cache/redis/service/CacheRedisService.java
  domain/search-domain-rdb/src/main/java/woowa/team4/bff/search/repository/RestaurantSummaryRepository.java
  event/cache-event/src/main/java/woowa/team4/bff/event/cache/RestaurantSummaryCacheEvent.java
Labels: ♻️Refactor

#128 [fix] restaurant-service 에서 가게, 메뉴 관련 이벤트 핸들링 해서 elastic search에 적용하는…
  service/restaurant-service/build.gradle
  service/restaurant-service/src/main/resources/application.yml
  service/search-service/src/main/resources/application.yml
  settings.gradle
  worker/worker-es/build.gradle
  worker/worker-es/src/main/java/woowa/team4/bff/worker/service/ElasticsearchEventHandler.java
Labels: 🐛Bug

#130 [fix] 동일 키워드와 동일 id가 오면 동일 광고가 응답되게 수정
  service/advertisement-service/src/main/java/woowa/team4/bff/advertisementservice/AdvertisementController.java
Labels: 🪓Hotfix

#126 [config] 서버 배포 스크립트 및 환경 구성
  .github/workflows/dev-deploy.yml
  service/cache-service/src/main/resources/application.yml
  service/coupon-service/build.gradle
  service/restaurant-exposure-service/src/main/resources/application.yml
  service/restaurant-service/src/main/resources/application.yml
  service/search-service/src/main/resources/application.yml
Labels: ⚙️Config

#136 [feature] 검색 인기 순 구현
  api-client/cache-client/src/main/java/woowa/team4/bff/api/client/cache/caller/CacheApiCaller.java
  api-client/cache-client/src/main/java/woowa/team4/bff/api/client/cache/config/CacheClientConfiguration.java
  api-client/cache-client/src/main/java/woowa/team4/bff/api/client/cache/request/RankingRequest.java
  domain/cache-domain-redis/src/main/java/woowa/team4/bff/cache/redis/domain/SearchRankingResponse.java
  domain/cache-domain-redis/src/main/java/woowa/team4/bff/cache/redis/service/RankingService.java
  domain/exposure-domain/src/main/java/woowa/team4/bff/exposure/service/RestaurantExposureListService.java
  service/cache-service/src/main/java/woowa/team4/bff/cacheservice/CacheController.java
  service/cache-service/src/main/java/woowa/team4/bff/cacheservice/RankingController.java
  service/cache-service/src/main/resources/application.yml
  service/restaurant-exposure-service/src/main/resources/application.yml
Labels: 💫Feature

#137 [fix] 비동기 호출 코드 수정
  domain/exposure-domain/src/main/java/woowa/team4/bff/exposure/service/RestaurantExposureListService.java
Labels: 💫Feature

#141 [refactor] Elasticsearch에서 검색할 때 restaurantId 필드만 조회하도록 변경
  core-web/src/main/java/woowa/team4/bff/common/exception/GeneralExceptionHandler.java
  domain/search-domain-es/src/main/java/woowa/team4/bff/search/service/ElasticsearchIndexInitializer.java
  domain/search-domain-es/src/main/java/woowa/team4/bff/search/service/SearchElasticsearchService.java
Labels: ♻️Refactor

#142 [feature] 가게 노출의 요청과 응답을 비동기로 처리한다.
  api-client/build.gradle
  api-client/search-client/src/main/java/woowa/team4/bff/api/client/caller/SearchApiCaller.java
  domain/build.gradle
  domain/cache-domain-redis/build.gradle
  domain/common-domain/build.gradle
  domain/exposure-domain/build.gradle
  domain/exposure-domain/src/main/java/woowa/team4/bff/exposure/service/RestaurantExposureListService.java
  domain/menu-domain-rdb/build.gradle
  domain/restaurant-domain-rdb/build.gradle
  domain/review-domain-rdb/build.gradle
  domain/search-domain-es/build.gradle
  domain/search-domain-rdb/build.gradle
  service/restaurant-exposure-service/build.gradle
  service/restaurant-exposure-service/src/main/java/woowa/team4/bff/RestaurantExposureServiceApplication.java
  service/restaurant-exposure-service/src/main/java/woowa/team4/bff/restauarntexposureservice/exposure/controller/RestaurantSummaryApiController.java
  service/restaurant-exposure-service/src/main/java/woowa/team4/bff/restauarntexposureservice/exposure/utils/ApiUtils.java
  service/restaurant-exposure-service/src/main/resources/application.yml
  settings.gradle
Labels: 💫Feature

#145 [feature] 인기 검색어 순위를 화면에 나타나게 한다.
  view/index.html
  view/package-lock.json
  view/package.json
  view/public/192.png
  view/public/512.png
  view/public/img/img1.jpg
  view/public/img/img10.jpg
  view/public/img/img2.jpg
  view/public/img/img3.jpg
  view/public/img/img4.jpg
  view/public/img/img5.jpg
  view/public/img/img6.jpg
  view/public/img/img7.jpg
  view/public/img/img8.jpg
  view/public/img/img9.jpg
  view/src/components/RestaurantList.jsx
  view/src/components/SearchRanking.jsx
  view/src/components/SearchRankingDisplay.jsx
  view/src/main.jsx
  view/vercel.json
  view/vite.config.js
Labels: 💫Feature

#146 [fix] GitHub Actions 배포 스크립트를 수정
  .github/workflows/dev-deploy.yml
Labels: 🐛Bug

#148 [docs] README를 업데이트 한다.
  README.md
Labels: 📝Docs

#149 [hotfix] README 오타 수정
  README.md
Labels: 🪓Hotfix
